### ISSUE TITLE
Notify about new sales

### ISSUE THREAD

**Issue by JordyMoos** [JordyMoos/JMGuildSaleHistoryTracker#10]
We need to have an api that informs listeners about new sales.
Best is if we just call the api in saveNewSaleList per guild. Sending the new sales through the api.

The other addon can then decide to add those new sales tho their own data or just use the api to get all of the guild sales

**Comment by JordyMoos** [comment]
Events:
- new guild sales

**Comment by marcusklaas** [comment]
Is there also an event for new auctions by the way?

**Comment by JordyMoos** [comment]
That is not this addon right? ;)
But yea when you created a new scan of the guild. An event will be thrown then we have a new snapshot and it will have that snapshot as its argument. So listening addons can change immediately work with the new data without asking for it. Ofcourse They need to be registered to the event

**Comment by marcusklaas** [comment]
You are correct, it is not very relevant to the addon ;p But this event would be yours then, and not a built-in one?

**Comment by JordyMoos** [comment]
Indeed, this event will be thrown when i added new sales to my sale history.
I buffer the sales first so it won't give conflicts if the player logs in or out at any time.
When i am done scanning. Then i will add the buffer to the history and then this new event will be thrown so 3rd party addons can work with the new sales.

Are we on one line here or did i misunderstand your comment? :)

**Comment by JordyMoos** [comment]
https://github.com/JordyMoos/JMGuildSaleHistoryTracker/pull/14
